# Generated by Django 5.1.5 on 2025-10-24 10:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('Brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand_name', models.CharField(max_length=50, null=True)),
                ('Brand_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(default='C01', max_length=50, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('Customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=25, unique=True)),
                ('Contact', models.PositiveBigIntegerField()),
                ('Profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_mode', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Quotes',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_id', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('size_value', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('variation_id', models.CharField(default='V01', max_length=50, primary_key=True, serialize=False)),
                ('variation_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'variation',
            },
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.PositiveIntegerField()),
                ('Sub_Total', models.PositiveIntegerField()),
                ('Cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartid', to='MHSapp.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='MHSapp.customers'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_id', models.AutoField(primary_key=True, serialize=False)),
                ('Address_type', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('House_No', models.PositiveIntegerField()),
                ('Area_Colony', models.CharField(max_length=75)),
                ('Landmark', models.CharField(max_length=100)),
                ('Pincode', models.PositiveIntegerField()),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('Country', models.CharField(max_length=25)),
                ('Contact', models.PositiveBigIntegerField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='MHSapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('homepageimage_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='homepage_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_images', to='MHSapp.category')),
            ],
            options={
                'db_table': 'homepage_image',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_msg', models.CharField(max_length=100, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='MHSapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateTimeField(auto_now_add=True)),
                ('payment_confirmation', models.CharField(max_length=20, null=True)),
                ('order_status', models.CharField(max_length=20, null=True)),
                ('Cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='MHSapp.cart')),
                ('Delivery_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='MHSapp.address')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentid', to='MHSapp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('order_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitemid', to='MHSapp.cart_item')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerid', to='MHSapp.customers')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderid', to='MHSapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default='PR001', max_length=50, primary_key=True, serialize=False)),
                ('product_description', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('Brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandid', to='MHSapp.brands')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Productvariation',
            fields=[
                ('product_variation_id', models.CharField(default='PV0001', max_length=50, primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productid', to='MHSapp.product')),
            ],
            options={
                'db_table': 'productvariation',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('product_images_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MHSapp.productvariation')),
            ],
            options={
                'db_table': 'mhs_app_product_img',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer_rating',
            fields=[
                ('customer_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='MHSapp.customers')),
                ('product_variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='MHSapp.productvariation')),
            ],
        ),
        migrations.AddField(
            model_name='cart_item',
            name='product_variation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariationid', to='MHSapp.productvariation'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('sub_category_id', models.CharField(default='SC001', max_length=50, primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryid', to='MHSapp.category')),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='MHSapp.subcategory'),
        ),
        migrations.CreateModel(
            name='Variationoption',
            fields=[
                ('variation_option_id', models.CharField(default='VO001', max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('ColorCode', models.CharField(blank=True, max_length=50, null=True)),
                ('variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variationid', to='MHSapp.variation')),
            ],
            options={
                'db_table': 'variationoption',
            },
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variationoptionid', to='MHSapp.variationoption'),
        ),
        migrations.CreateModel(
            name='Varieties',
            fields=[
                ('Variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('Variety_image', models.ImageField(upload_to='variety_images/')),
                ('Brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='MHSapp.brands')),
                ('Variation_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_options', to='MHSapp.variationoption')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customid', to='MHSapp.customers')),
                ('product_variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodid', to='MHSapp.productvariation')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='User_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
