# Generated by Django 5.1.5 on 2025-08-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='Brand_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
