# Generated by Django 5.2.7 on 2025-10-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHSapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='User_id',
            new_name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='availability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
