# Generated by Django 5.1.5 on 2025-09-01 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHSapp', '0002_alter_brands_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('homepageimage_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='homepage_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_images', to='MHSapp.category')),
            ],
            options={
                'db_table': 'homepage_image',
            },
        ),
    ]
