# Generated by Django 5.1.5 on 2025-09-03 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHSapp', '0003_homepageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customid', to='MHSapp.customers')),
                ('product_variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodid', to='MHSapp.productvariation')),
            ],
        ),
    ]
