# Generated by Django 5.1.5 on 2025-09-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHSapp', '0005_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='Brand_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
