# Generated by Django 5.1.5 on 2025-09-26 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHSapp', '0006_brands_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varieties',
            fields=[
                ('Variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('Variety_image', models.ImageField(upload_to='variety_images/')),
                ('Brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='MHSapp.brands')),
                ('Variation_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_options', to='MHSapp.variationoption')),
            ],
        ),
    ]
