# Generated by Django 5.1.5 on 2025-09-30 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHSapp', '0007_varieties'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Customer_rating',
            fields=[
                ('customer_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='MHSapp.customers')),
                ('product_variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='MHSapp.productvariation')),
            ],
        ),
    ]
