# Generated by Django 5.1.5 on 2025-10-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHSapp', '0008_productvariation_avg_rating_customer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
